# This rule is not used by the project bold-chatelet itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to core.bootchain-operator.ruicoelho.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bold-chatelet
    app.kubernetes.io/managed-by: kustomize
  name: bootdependency-viewer-role
rules:
- apiGroups:
  - core.bootchain-operator.ruicoelho.dev
  resources:
  - bootdependencies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.bootchain-operator.ruicoelho.dev
  resources:
  - bootdependencies/status
  verbs:
  - get
