# This rule is not used by the project bold-chatelet itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.bootchain.ruicoelho.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bold-chatelet
    app.kubernetes.io/managed-by: kustomize
  name: bootdependency-admin-role
rules:
- apiGroups:
  - core.bootchain.ruicoelho.dev
  resources:
  - bootdependencies
  verbs:
  - '*'
- apiGroups:
  - core.bootchain.ruicoelho.dev
  resources:
  - bootdependencies/status
  verbs:
  - get
