apiVersion: core.bootchain-operator.ruicoelho.dev/v1alpha1
kind: BootDependency
metadata:
  name: payments-api
  namespace: default
spec:
  dependsOn:
    # in-cluster Kubernetes Service
    - service: payments-db
      port: 5432
      timeout: 60s
    - service: redis
      port: 6379
      timeout: 30s
    # external dependency (outside the cluster)
    - host: vault.internal.mycompany.com
      port: 8200
      timeout: 30s
