version: 1.0.0
name: bootchain-operator
displayName: Bootchain Operator
description: Helm chart that deploys the Bootchain Operator.
keywords:
- kubernetes
- operator
- init-containers
- boot-dependencies
home: https://github.com/user-cube/bootchain-operator
sources:
- https://github.com/user-cube/bootchain-operator
license: Apache-2.0
maintainers:
- name: user-cube
annotations:
  artifacthub.io/category: kubernetes
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: user-cube
createdAt: '2026-02-28T03:57:08Z'
changes:
- kind: fixed
  description: add missing requirements
  links:
  - name: Commit dd46677
    url: https://github.com/user-cube/bootchain-operator/commit/dd46677d0420b30a16050ad45b10551f0382d608
- kind: fixed
  description: bump app version
  links:
  - name: Commit dc26cdf
    url: https://github.com/user-cube/bootchain-operator/commit/dc26cdf1a81c87f7435c0c969edc225418419082
- kind: fixed
  description: bump app version
  links:
  - name: Commit 79738c2
    url: https://github.com/user-cube/bootchain-operator/commit/79738c2458dea6e170bcfaaedd71f37910a604c4
- kind: fixed
  description: fix python version
  links:
  - name: Commit 11c979b
    url: https://github.com/user-cube/bootchain-operator/commit/11c979b844d4bb80f32c337dd5d92f32e1fa0148
- kind: fixed
  description: Merge branch 'main' of github.com:user-cube/bootchain-operator
  links:
  - name: Commit 30c55bf
    url: https://github.com/user-cube/bootchain-operator/commit/30c55bf631fe3884a5e1e180fdbc7a4750a6ec6d
- kind: fixed
  description: update docs and actions
  links:
  - name: Commit 03166f8
    url: https://github.com/user-cube/bootchain-operator/commit/03166f8da560ee7c2943442b602a1e440ded8099
- kind: added
  description: add Helm chart for cluster deployment
  links:
  - name: Commit 57ca84c
    url: https://github.com/user-cube/bootchain-operator/commit/57ca84cf6f825edc0b5f9c6841dbee164500895b
- kind: added
  description: add MkDocs documentation site
  links:
  - name: Commit 68e2b57
    url: https://github.com/user-cube/bootchain-operator/commit/68e2b576d690d39910bb629ae135bbd5820a45e4
- kind: added
  description: add Prometheus metrics to controller
  links:
  - name: Commit f2b32b1
    url: https://github.com/user-cube/bootchain-operator/commit/f2b32b1bfeb2dcc5e5b36c1e9844d06fcaa8bc36
- kind: added
  description: cicd
  links:
  - name: Commit 02b5cd1
    url: https://github.com/user-cube/bootchain-operator/commit/02b5cd112095577b311cb3545de10a2c34c4229c
- kind: added
  description: crd; webhooks; controller
  links:
  - name: Commit a09d440
    url: https://github.com/user-cube/bootchain-operator/commit/a09d44065b81cc3a1cab022399f0f2303ce9fe4c
- kind: added
  description: reset semantic release
  links:
  - name: Commit be8d4bb
    url: https://github.com/user-cube/bootchain-operator/commit/be8d4bb735eb5adbd9a8f5c2c00c6520ede046f8
- kind: added
  description: reset semantic release
  links:
  - name: Commit 9a464c6
    url: https://github.com/user-cube/bootchain-operator/commit/9a464c650c0ab273742eb1aae275bf902aa04e4e
- kind: added
  description: reset semantic release
  links:
  - name: Commit f80b206
    url: https://github.com/user-cube/bootchain-operator/commit/f80b206419278fc1b732e5fb48dfd3d5e544d821
- kind: added
  description: reset semantic release
  links:
  - name: Commit 209b470
    url: https://github.com/user-cube/bootchain-operator/commit/209b47087662691daf6583e08a57762dc395a81d
- kind: added
  description: reset semantic release
  links:
  - name: Commit 9d3d164
    url: https://github.com/user-cube/bootchain-operator/commit/9d3d1644487270829006885dd6ed7e6a276c13e3
