version: 1.2.4
name: bootchain-operator
displayName: Bootchain Operator
description: Helm chart that deploys the Bootchain Operator.
keywords:
- kubernetes
- operator
- init-containers
- boot-dependencies
home: https://github.com/user-cube/bootchain-operator
sources:
- https://github.com/user-cube/bootchain-operator
license: Apache-2.0
maintainers:
- name: user-cube
annotations:
  artifacthub.io/category: kubernetes
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: user-cube
createdAt: '2026-03-01T00:29:05Z'
changes:
- kind: fixed
  description: add safeguards for timeouts ([#13](https://github.com/user-cube/bootchain-operator/issues/13))
  links:
  - name: Commit 5a44651
    url: https://github.com/user-cube/bootchain-operator/commit/5a446512af5e00b794224fa0835ed8e61ec41400
