version: 1.2.3
name: bootchain-operator
displayName: Bootchain Operator
description: Helm chart that deploys the Bootchain Operator.
keywords:
- kubernetes
- operator
- init-containers
- boot-dependencies
home: https://github.com/user-cube/bootchain-operator
sources:
- https://github.com/user-cube/bootchain-operator
license: Apache-2.0
maintainers:
- name: user-cube
annotations:
  artifacthub.io/category: kubernetes
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: user-cube
createdAt: '2026-03-01T00:03:48Z'
changes:
- kind: fixed
  description: update minimal tools version
  links:
  - name: Commit 31a9f93
    url: https://github.com/user-cube/bootchain-operator/commit/31a9f93b82442a23453a6dfbde086690f77782b2
