apiVersion: v2
name: bootchain-operator
description: >-
  A Kubernetes operator that makes service boot dependencies declarative and
  automatic, eliminating hand-written init containers.
type: application
version: 1.0.4
appVersion: 1.0.5
keywords:
  - kubernetes
  - operator
  - init-containers
  - boot-dependencies
home: https://github.com/user-cube/bootchain-operator
sources:
  - https://github.com/user-cube/bootchain-operator
maintainers:
  - name: user-cube
kubeVersion: '>=1.25.0'
