{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bootchain-operator.fullname" . }}
  namespace: {{ include "bootchain-operator.namespace" . }}
  labels:
    {{- include "bootchain-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "bootchain-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
  - port: metrics
    path: /metrics
    scheme: http
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
